export function buildStayBlocksPrompt(propertyName: string): string {
  const name = propertyName?.trim() || "Your property";
  return [
    "# AppointzaStay Blocks Master Prompt",
    "",
    `Design a hotel / stay booking website for "${name}" as a blocks JSON array.`,
    "",
    "## OUTPUT",
    "",
    "Return ONLY a JSON array of page blocks (no Markdown fences, no commentary).",
    "",
    "Each block:",
    "",
    "{",
    '  "id": "uuid-or-unique-string",',
    '  "type": "hotel-hero",',
    '  "props": { },',
    '  "layout": {',
    '    "width": 100,',
    '    "height": "auto",',
    '    "padding": { "top": 80, "right": 40, "bottom": 80, "left": 40 },',
    '    "margin": { "top": 0, "right": 0, "bottom": 0, "left": 0 }',
    "  }",
    "}",
    "",
    "## IMPORTANT",
    "",
    "- Prefer Hotel block types so live room / amenity / gallery data can hydrate.",
    "- Do not invent room names, prices, photos, or policies — use empty arrays or short marketing copy only.",
    "- Keep props keys simple (title, subtitle, brand, primaryCta, etc.).",
    "- Use unique ids for every block.",
    "- Return JSON only.",
    "",
    "## Availability / Book now",
    "",
    "- hotel-rooms and hotel-all-rooms hydrate live rooms from the property.",
    "- Each live room includes available (true only when status is available).",
    "- The renderer shows \"Book this room\" only when available === true; otherwise it shows \"Not available\" (no booking link).",
    "- Do NOT invent room.available, bookUrl, or status fields — leave rooms empty so live data fills them.",
    "- Hero primaryCta can say \"Book now\" / \"Book a room\"; the live site wires it to booking when rooms are bookable.",
    "",
    "## Recommended order (Hotel)",
    "",
    "1. hotel-hero",
    "2. hotel-about",
    "3. hotel-rooms or hotel-all-rooms",
    "4. hotel-amenities",
    "5. hotel-gallery",
    "6. hotel-packages",
    "7. hotel-reviews",
    "8. hotel-nearby",
    "9. hotel-booking",
    "10. hotel-policies",
    "11. hotel-payment",
    "12. hotel-contact",
    "13. footer (optional)",
    "",
    "## Allowed Hotel types",
    "",
    "- hotel-hero",
    "- hotel-about",
    "- hotel-rooms",
    "- hotel-all-rooms",
    "- hotel-amenities",
    "- hotel-gallery",
    "- hotel-booking",
    "- hotel-packages",
    "- hotel-reviews",
    "- hotel-nearby",
    "- hotel-contact",
    "- hotel-policies",
    "- hotel-payment",
    "",
    "## Also allowed structure types",
    "",
    "- nav, hero, hero-split, features, services, stats, pricing, testimonials, faq, contact, cta, footer",
    "",
    "## Example",
    "",
    "[",
    "  {",
    '    "id": "hero-1",',
    '    "type": "hotel-hero",',
    '    "props": {',
    `      "brand": "${name}",`,
    `      "title": "Welcome to ${name}",`,
    '      "subtitle": "Comfortable stays with easy online booking.",',
    '      "primaryCta": "Book now"',
    "    },",
    '    "layout": {',
    '      "width": 100,',
    '      "height": "auto",',
    '      "padding": { "top": 80, "right": 40, "bottom": 80, "left": 40 },',
    '      "margin": { "top": 0, "right": 0, "bottom": 0, "left": 0 }',
    "    }",
    "  }",
    "]",
    "",
    "## Validation",
    "",
    "- Top-level value must be a JSON array",
    "- Only use allowed types",
    "- No invented live room data",
    "- Book CTAs rely on live availability — do not hardcode always-bookable rooms",
    "- Return JSON only",
  ].join("\n");
}
