export function buildStayHtmlPrompt(propertyName: string): string {
  const name = propertyName?.trim() || "Your property";
  return [
    "# AppointzaStay Master Prompt",
    "",
    `Create a modern, mobile-friendly booking website for "${name}".`,
    "",
    "## OUTPUT",
    "",
    "Return one complete HTML document with embedded CSS only.",
    "",
    "## IMPORTANT",
    "",
    "- This is a multi-tenant app: every variable is filled from the current organisation only.",
    "- {{organisation.id}} is the tenant key — never hardcode organisation IDs.",
    "- Preserve ALL AppointzaStay variables exactly.",
    "- Never invent or rename variables.",
    "- Never hardcode booking URLs, room IDs, or package IDs.",
    "- Improve only the UI.",
    "- Plain HTML and CSS only. No React, Vue, JavaScript, Markdown, or explanations.",
    "- Return HTML only.",
    "",
    "## Variables",
    "",
    "### Organisation",
    "",
    "{{organisation.id}}",
    "{{organisation.name}}",
    "{{organisation.tagline}}",
    "{{organisation.description}}",
    "{{organisation.address}}",
    "{{organisation.city}}",
    "{{organisation.state}}",
    "{{organisation.country}}",
    "{{organisation.phone}}",
    "{{organisation.whatsapp}}",
    "{{organisation.email}}",
    "{{organisation.check_in_time}}",
    "{{organisation.check_out_time}}",
    "{{organisation.cancellation_policy}}",
    "{{organisation.payment_policy}}",
    "{{organisation.website_url}}",
    "{{organisation.subdomain}}",
    "{{organisation.logo_url}}",
    "{{currentyear}}",
    "",
    "### Booking",
    "",
    "{{BOOK_URL}}",
    "{{ROOM_BOOK_URL}}",
    "{{PACKAGE_BOOK_URL}}",
    "",
    "### Availability conditionals",
    "",
    "{{#if_has_bookable_rooms}} … {{/if_has_bookable_rooms}}",
    "{{#if_no_bookable_rooms}} … {{/if_no_bookable_rooms}}",
    "{{#if_room_available}} … {{/if_room_available}}  (inside {{#rooms}} only)",
    "{{#if_room_unavailable}} … {{/if_room_unavailable}}  (inside {{#rooms}} only)",
    "",
    "### Rooms",
    "",
    "{{#rooms}}",
    "{{room.id}}",
    "{{room.number}}",
    "{{room.name}}",
    "{{room.type}}",
    "{{room.price}}",
    "{{room.weekend_price}}",
    "{{room.capacity}}",
    "{{room.main_photo}}",
    "{{room.video_url}}",
    "{{room.status}}",
    "{{room.status_label}}",
    "{{room.available}}",
    "{{room.book_cta}}",
    "{{ROOM_BOOK_URL}}",
    "{{/rooms}}",
    "",
    "### Gallery",
    "",
    "{{#gallery}}",
    "{{image.url}}",
    "{{image.label}}",
    "{{image.category}}",
    "{{image.video_url}}",
    "{{image.tour360_url}}",
    "{{/gallery}}",
    "",
    "### Amenities",
    "",
    "{{#amenities}}",
    "{{amenity.icon}}",
    "{{amenity.name}}",
    "{{amenity.description}}",
    "{{amenity.group}}",
    "{{/amenities}}",
    "",
    "### Reviews",
    "",
    "{{#reviews}}",
    "{{review.author}}",
    "{{review.rating}}",
    "{{review.quote}}",
    "{{review.date}}",
    "{{/reviews}}",
    "",
    "### Packages",
    "",
    "{{#packages}}",
    "{{package.id}}",
    "{{package.name}}",
    "{{package.price}}",
    "{{package.description}}",
    "{{package.badge}}",
    "{{package.image_url}}",
    "{{package.valid_from}}",
    "{{package.valid_to}}",
    "{{package.minimum_nights}}",
    "{{package.max_guests}}",
    "{{package.room_type}}",
    "{{package.includes}}",
    "{{package.addons}}",
    "{{package.kind}}",
    "{{PACKAGE_BOOK_URL}}",
    "{{/packages}}",
    "",
    "### Nearby places",
    "",
    "{{#nearby_places}}",
    "{{place.name}}",
    "{{place.distance}}",
    "{{place.travel_time}}",
    "{{place.icon}}",
    "{{place.image_url}}",
    "{{place.map_url}}",
    "{{/nearby_places}}",
    "",
    "### Activities",
    "",
    "{{#activities}}",
    "{{activity.title}}",
    "{{activity.description}}",
    "{{activity.icon}}",
    "{{/activities}}",
    "",
    "### FAQ",
    "",
    "{{#faq}}",
    "{{faq.question}}",
    "{{faq.answer}}",
    "{{/faq}}",
    "",
    "## Rules",
    "",
    "- Only cards or media items repeat inside loops.",
    "- Never put sections, headings, grids, or outer containers inside loops.",
    "- Use CSS Grid and Flexbox.",
    "- Use a mobile-first responsive design.",
    "- Use a luxury hospitality aesthetic.",
    "- Include Header, Hero, About, Rooms, Amenities, Gallery, Packages, Reviews, Nearby Places, Activities, FAQ, Contact, and Footer when data is available.",
    "- Never create fake rooms, reviews, prices, addresses, images, or videos.",
    "- Hide optional sections when their loop has no items.",
    "",
    "### Booking links (availability rules)",
    "",
    "CRITICAL: Show Book now / Book this room ONLY when the room (or property) is available.",
    "{{ROOM_BOOK_URL}} is empty when the room is not available.",
    "{{BOOK_URL}} is empty when no rooms are available for booking.",
    "",
    "General Book now — wrap with availability conditional:",
    "",
    "{{#if_has_bookable_rooms}}",
    '<a href="{{BOOK_URL}}" target="_top">Book now</a>',
    "{{/if_has_bookable_rooms}}",
    "{{#if_no_bookable_rooms}}",
    "<span>No rooms available right now</span>",
    "{{/if_no_bookable_rooms}}",
    "",
    "Room booking — inside {{#rooms}} only, gated by availability:",
    "",
    "{{#if_room_available}}",
    '<a href="{{ROOM_BOOK_URL}}" target="_top">Book this room</a>',
    "{{/if_room_available}}",
    "{{#if_room_unavailable}}",
    "<span>{{room.status_label}}</span>",
    "{{/if_room_unavailable}}",
    "",
    "Package booking — inside {{#packages}} only:",
    "",
    '<a href="{{PACKAGE_BOOK_URL}}" target="_top">Book package</a>',
    "",
    "Never link booking buttons to /explore, #rooms, or invented URLs.",
    "Always use target=\"_top\" on booking links.",
    "Never show a Book now / Book this room button for unavailable rooms.",
    "Add CSS to hide empty booking links:",
    'a[href=""] { display: none; }',
    "",
    "### Logo",
    "",
    '<img src="{{organisation.logo_url}}" alt="{{organisation.name}}">',
    "",
    "Add CSS to hide an empty logo:",
    'img[src=""] { display: none; }',
    "",
    "### Room cards",
    "",
    "Correct structure:",
    "",
    '<section id="rooms">',
    "  <h2>Rooms</h2>",
    '  <div class="rooms-grid">',
    "    {{#rooms}}",
    '    <article class="room-card">',
    '      <img src="{{room.main_photo}}" alt="{{room.name}}">',
    '      <video controls playsinline preload="metadata" src="{{room.video_url}}"></video>',
    "      <h3>{{room.name}}</h3>",
    "      <p>{{room.type}} · {{room.capacity}} guests</p>",
    "      <p>From ₹{{room.price}} / night</p>",
    "      <p>{{room.status_label}}</p>",
    "      {{#if_room_available}}",
    '      <a href="{{ROOM_BOOK_URL}}" target="_top">Book this room</a>',
    "      {{/if_room_available}}",
    "      {{#if_room_unavailable}}",
    "      <span>Not available</span>",
    "      {{/if_room_unavailable}}",
    "    </article>",
    "    {{/rooms}}",
    "  </div>",
    "</section>",
    "",
    "### Gallery",
    "",
    "Repeat only one gallery item inside the loop.",
    "Use {{image.url}} for photos.",
    "",
    "### Videos",
    "",
    "Use {{room.video_url}} inside room cards and {{image.video_url}} inside gallery items when available.",
    "For direct MP4 or hosted file links use:",
    "",
    '<video controls playsinline preload="metadata" src="{{room.video_url}}"></video>',
    "",
    "For YouTube or Vimeo links stored in video_url, use an iframe only when the URL is already an embed link.",
    "Never invent video URLs.",
    "Hide empty players with CSS:",
    "video:not([src]), video[src=\"\"], iframe:not([src]), iframe[src=\"\"] { display: none; }",
    "Make video players responsive with width: 100% and aspect-ratio: 16/9.",
    "",
    "### Map / location",
    "",
    "Build the map from organisation address fields. Never use /maps/embed?pb= URLs.",
    "Use:",
    "",
    '<iframe title="{{organisation.name}} map" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen',
    '  src="https://www.google.com/maps?q={{organisation.address}},{{organisation.city}},{{organisation.state}},{{organisation.country}}&output=embed"></iframe>',
    "",
    "## Validation",
    "",
    "- Exactly one Hero.",
    "- Exactly one Rooms section.",
    "- Exactly one Rooms grid.",
    "- Only room cards repeat inside the rooms loop.",
    "- Only gallery items repeat inside the gallery loop.",
    "- Book now / Book this room only inside availability conditionals (or when href is non-empty).",
    "- No nested sections.",
    "- No repeated headings.",
    "- No invented or altered variables.",
    "- No hardcoded booking URLs.",
    "- Return HTML only.",
  ].join("\n");
}
