import { buildBookAppointmentPath, buildRoomBookPath } from "@/utils/templateBookingNav.util";
import { environment, getApiBaseUrl, getUiBaseUrl } from "@/utils/environment";

export type TemplateVariableGroup = {
  title: string;
  items: { token: string; description: string; example?: string }[];
};

/** Page sections aligned with Live — Business / Hospitality builder blocks. */
export const TEMPLATE_PAGE_SECTIONS = [
  {
    name: "Business home",
    summary: "Name, tagline, logo, about text, Book button",
    variables: [
      "{{organisationdetail.id}}",
      "{{organisationdetail.name}}",
      "{{organisationdetail.tagline}}",
      "{{organisationdetail.notes}}",
      "{{organisation.notes}}",
      "{{OrganisationNotes}}",
      "{{organisationdetail.gstnumber}}",
      "{{organisationemail}}",
      "{{#organizationlogo}}",
      "{{ORGANISATION_LOGO_URL}}",
      "{{organisationdetail.organisationlogo}}",
      "{{/organizationlogo}}",
      "{{BOOKNOWURL}}",
      "{{currentyear}}",
    ],
  },
  {
    name: "Location",
    summary: "Address, map embed, phone, Google Maps link",
    variables: [
      "{{locationdetail.id}}",
      "{{locationdetail.name}}",
      "{{locationdetail.addressline1}}",
      "{{#addressline2}}{{locationdetail.addressline2}}{{/addressline2}}",
      "{{locationdetail.city}}",
      "{{locationdetail.state}}",
      "{{#country}}{{locationdetail.country}}{{/country}}",
      "{{locationdetail.pincode}}",
      "{{locationdetail.mobile}}",
      "{{#googlemaps}}{{locationdetail.googlelocation}}{{/googlemaps}}",
      "{{#coordinates}}{{locationdetail.latitude}},{{locationdetail.longitude}}{{/coordinates}}",
    ],
  },
  {
    name: "Services catalog",
    summary: "Service catalog — section title OUTSIDE loop; ONE card per {{#orgnaisatinservice}} iteration",
    variables: [
      "{{#orgnaisatinservice}}",
      "{{Servicename}}",
      "{{prize}}",
      "{{timetaken}}",
      "{{notes}}",
      "{{service_id}}",
      "{{SERVICE_BOOK_URL}}",
      "{{#service_image_id}}",
      "{{SERVICE_IMAGE_URL}}",
      "{{service_image_id}}",
      "{{/service_image_id}}",
      "{{/orgnaisatinservice}}",
    ],
  },
  {
    name: "Working hours",
    summary: "Opening hours / timings",
    variables: [
      "{{#OrganisationServiceTiming}}",
      "{{day_name}}",
      "{{day_of_week}}",
      "{{start_time}}",
      "{{end_time}}",
      "{{/OrganisationServiceTiming}}",
    ],
  },
  {
    name: "Events & workshops",
    summary: "Public events list with register links",
    variables: [
      "{{#hasevents}}",
      "{{#events}}",
      "{{event_name}}",
      "{{event_date}}",
      "{{from_date}}",
      "{{#to_date}}{{to_date}}{{/to_date}}",
      "{{entry_amount}}",
      "{{remainingslot}}",
      "{{description}}",
      "{{status}}",
      "{{EVENTBOOKURL}}",
      "{{#event_image_id}}",
      "{{EVENT_IMAGE_URL}}",
      "{{event_image_id}}",
      "{{event_image_url}}",
      "{{/event_image_id}}",
      "{{/events}}",
      "{{/hasevents}}",
    ],
  },
  {
    name: "Amenities / facilities",
    summary: "Facility checklist — show section only if amenities exist",
    variables: ["{{#facilities}}", "{{facility_displaytext}}", "{{/facilities}}"],
  },
  {
    name: "Photo gallery",
    summary: "Location photo grid — prefer LOCATION_IMAGE_URL",
    variables: [
      "{{#locationimages}}",
      "{{LOCATION_IMAGE_URL}}",
      "{{location_image_id}}",
      "{{/locationimages}}",
    ],
  },
  {
    name: "Video gallery",
    summary: "Location video gallery — show only when video URLs exist",
    variables: [
      "{{#locationvideos}}",
      "{{LOCATION_VIDEO_EMBED_URL}}",
      "{{LOCATION_VIDEO_URL}}",
      "{{/locationvideos}}",
    ],
  },
  {
    name: "Customer reviews",
    summary: "Customer reviews (shows when review data exists) — prefer static Testimonials for editable quotes",
    variables: ["{{#reviews}}", "{{rating_stars}}", "{{comment}}", "{{/reviews}}"],
  },
  {
    name: "Rooms (Hospitality)",
    summary: "Bookable rooms — wrap with {{#hasrooms}}; one card per {{#rooms}}",
    variables: [
      "{{#hasrooms}}",
      "{{#rooms}}",
      "{{room.id}}",
      "{{room.room_number}}",
      "{{room.room_name}}",
      "{{room.name}}",
      "{{room.type}}",
      "{{room.capacity}}",
      "{{room.price}}",
      "{{room.main_photo}}",
      "{{room.video_url}}",
      "{{room.status}}",
      "{{room.status_label}}",
      "{{#if_room_available}}",
      "{{ROOM_BOOK_URL}}",
      "{{/if_room_available}}",
      "{{#if_room_unavailable}}",
      "{{/if_room_unavailable}}",
      "{{/rooms}}",
      "{{/hasrooms}}",
    ],
  },
  {
    name: "Policies (Hospitality)",
    summary: "Check-in/out, cancellation & payment policies",
    variables: [
      "{{hospitality.check_in_time}}",
      "{{hospitality.check_out_time}}",
      "{{hospitality.cancellation_policy}}",
      "{{hospitality.payment_policy}}",
      "{{organisation.check_in_time}}",
      "{{organisation.check_out_time}}",
      "{{organisation.cancellation_policy}}",
      "{{organisation.payment_policy}}",
    ],
  },
  {
    name: "Packages (Hospitality)",
    summary: "Stay packages — wrap with {{#haspackages}}",
    variables: [
      "{{#haspackages}}",
      "{{#packages}}",
      "{{package.id}}",
      "{{package.name}}",
      "{{package.price}}",
      "{{package.description}}",
      "{{package.badge}}",
      "{{package.image_url}}",
      "{{package.minimum_nights}}",
      "{{package.max_guests}}",
      "{{package.room_type}}",
      "{{package.includes}}",
      "{{PACKAGE_BOOK_URL}}",
      "{{/packages}}",
      "{{/haspackages}}",
    ],
  },
  {
    name: "Food menu (Hospitality)",
    summary: "Meals & dining — wrap with {{#hasfoodmenu}}",
    variables: [
      "{{#hasfoodmenu}}",
      "{{#food_menu}}",
      "{{food.meal}}",
      "{{food.title}}",
      "{{food.description}}",
      "{{food.cuisines}}",
      "{{/food_menu}}",
      "{{/hasfoodmenu}}",
    ],
  },
  {
    name: "Nearby places (Hospitality)",
    summary: "Local attractions — wrap with {{#hasnearby}}",
    variables: [
      "{{#hasnearby}}",
      "{{#nearby_places}}",
      "{{place.name}}",
      "{{place.distance}}",
      "{{place.travel_time}}",
      "{{place.icon}}",
      "{{place.image_url}}",
      "{{place.map_url}}",
      "{{/nearby_places}}",
      "{{/hasnearby}}",
    ],
  },
  {
    name: "Guest services (Hospitality)",
    summary: "Guest add-ons — wrap with {{#hasguestservices}}",
    variables: [
      "{{#hasguestservices}}",
      "{{#guest_services}}",
      "{{guest.name}}",
      "{{guest.price}}",
      "{{guest.description}}",
      "{{guest.category}}",
      "{{guest.icon}}",
      "{{/guest_services}}",
      "{{/hasguestservices}}",
    ],
  },
] as const;

export const TEMPLATE_VARIABLE_GROUPS: TemplateVariableGroup[] = [
  {
    title: "Organisation",
    items: [
      { token: "{{organisationdetail.id}}", description: "Organisation ID" },
      { token: "{{organisationdetail.name}}", description: "Business name" },
      { token: "{{organisationdetail.tagline}}", description: "Tagline" },
      { token: "{{organisationdetail.notes}}", description: "About / description" },
      { token: "{{organisation.notes}}", description: "About alias (same as organisationdetail.notes)" },
      { token: "{{OrganisationNotes}}", description: "About alias (same as organisationdetail.notes)" },
      {
        token: "{{organisationdetail.gstnumber}}",
        description: "GST number — use this token (not organisationgstnumber)",
      },
      {
        token: "{{#gstnumber}} ... {{/gstnumber}}",
        description: "Show GST block only when gstnumber is set",
      },
      {
        token: "{{organisationemail}}",
        description: "Organisation email (may be empty — optional; spelling is organisationemail)",
      },
      {
        token: "{{#organizationlogo}} ... {{/organizationlogo}}",
        description: "Show logo only if uploaded — wrap the img tag inside this block",
        example:
          '{{#organizationlogo}}<img src="{{ORGANISATION_LOGO_URL}}" alt="{{organisationdetail.name}}" style="max-height:56px;width:auto;object-fit:contain" />{{/organizationlogo}}',
      },
      {
        token: "{{ORGANISATION_LOGO_URL}}",
        description: "Full logo image URL (prefer this inside {{#organizationlogo}})",
      },
      {
        token: "{{organisationdetail.organisationlogo}}",
        description: "Logo file ID (optional — prefer {{ORGANISATION_LOGO_URL}})",
      },
      { token: "{{currentyear}}", description: "Footer year (auto)" },
      {
        token: "{{organisation.check_in_time}} / {{organisation.cancellation_policy}} / …",
        description: "Optional hospitality policy aliases (same values as hospitality.*)",
      },
    ],
  },
  {
    title: "Location",
    items: [
      { token: "{{locationdetail.id}}", description: "Location ID" },
      { token: "{{locationdetail.name}}", description: "Location name" },
      { token: "{{locationdetail.addressline1}}", description: "Street address" },
      { token: "{{locationdetail.addressline2}}", description: "Address line 2" },
      { token: "{{locationdetail.city}}", description: "City" },
      { token: "{{locationdetail.state}}", description: "State" },
      { token: "{{locationdetail.country}}", description: "Country" },
      { token: "{{locationdetail.pincode}}", description: "PIN / postal code" },
      { token: "{{locationdetail.latitude}}", description: "Latitude" },
      { token: "{{locationdetail.longitude}}", description: "Longitude" },
      { token: "{{locationdetail.googlelocation}}", description: "Google Maps link URL (use in <a href>, never iframe src)" },
      { token: "{{locationdetail.mobile}}", description: "Phone / WhatsApp" },
      { token: "{{#googlemaps}} ... {{/googlemaps}}", description: "Maps link — only if set" },
      { token: "{{#coordinates}} ... {{/coordinates}}", description: "Lat/lng map embed — only if set" },
      { token: "{{#country}} ... {{/country}}", description: "Country — only if set" },
      { token: "{{#addressline2}} ... {{/addressline2}}", description: "Line 2 — only if set" },
    ],
  },
  {
    title: "Booking URLs",
    items: [
      {
        token: "{{BOOKNOWURL}}",
        description: "General book-appointment link (org + location)",
        example: '<a href="{{BOOKNOWURL}}" data-appointza-book>Book now</a>',
      },
      {
        token: "{{SERVICE_BOOK_URL}}",
        description: "Per-service book link — use INSIDE {{#orgnaisatinservice}}, not BOOKNOWURL",
        example: '<a href="{{SERVICE_BOOK_URL}}" data-appointza-book>Book</a>',
      },
      { token: "{{EVENTBOOKURL}}", description: "Event registration link (inside {{#events}})" },
      {
        token: "{{ROOM_BOOK_URL}}",
        description: "Book this room (inside {{#rooms}}, when available)",
        example: '<a href="{{ROOM_BOOK_URL}}">Book this room</a>',
      },
      {
        token: "{{PACKAGE_BOOK_URL}}",
        description: "Book this package (inside {{#packages}})",
        example: '<a href="{{PACKAGE_BOOK_URL}}">Book package</a>',
      },
    ],
  },
  {
    title: "Services",
    items: [
      {
        token: "{{#orgnaisatinservice}} ... {{/orgnaisatinservice}}",
        description: "Repeat ONE service card only — never put section headers inside this loop",
      },
      { token: "{{Servicename}}", description: "Service name" },
      { token: "{{prize}}", description: "Price" },
      { token: "{{timetaken}}", description: "Duration (minutes)" },
      { token: "{{notes}}", description: "Description" },
      { token: "{{service_id}}", description: "Service ID (inside service loop)" },
      {
        token: "{{SERVICE_BOOK_URL}}",
        description: "Book link for this service (org + location + service id)",
      },
      {
        token: "{{SERVICE_IMAGE_URL}}",
        description: "Full service image URL (inside service loop, when image exists)",
        example:
          '{{#service_image_id}}<img src="{{SERVICE_IMAGE_URL}}" alt="{{Servicename}}" style="max-height:200px;width:100%;object-fit:cover" />{{/service_image_id}}',
      },
      {
        token: "{{#service_image_id}} ... {{/service_image_id}}",
        description: "Show service image only when an image exists",
      },
      { token: "{{service_image_id}}", description: "Service image id/url (prefer {{SERVICE_IMAGE_URL}})" },
    ],
  },
  {
    title: "Working hours",
    items: [
      { token: "{{#OrganisationServiceTiming}} ... {{/OrganisationServiceTiming}}", description: "One row per day" },
      { token: "{{day_name}}", description: "Day name" },
      { token: "{{day_of_week}}", description: "Day number (1–7)" },
      { token: "{{start_time}}", description: "Opens" },
      { token: "{{end_time}}", description: "Closes" },
    ],
  },
  {
    title: "Events",
    items: [
      { token: "{{#hasevents}} ... {{/hasevents}}", description: "Wrap events section — hidden if no events" },
      { token: "{{#events}} ... {{/events}}", description: "One card per event" },
      { token: "{{event_name}}", description: "Event title" },
      { token: "{{event_date}}", description: "Date" },
      { token: "{{from_date}}", description: "Start date" },
      { token: "{{to_date}}", description: "End date" },
      { token: "{{#to_date}} ... {{/to_date}}", description: "Show end date only when set" },
      { token: "{{entry_amount}}", description: "Ticket price" },
      { token: "{{remainingslot}}", description: "Remaining slots" },
      { token: "{{description}}", description: "Event description" },
      { token: "{{status}}", description: "Event status" },
      { token: "{{EVENTBOOKURL}}", description: "Register link" },
      {
        token: "{{EVENT_IMAGE_URL}}",
        description: "Full event image URL (inside events loop)",
        example:
          '{{#event_image_id}}<img src="{{EVENT_IMAGE_URL}}" alt="{{event_name}}" style="max-height:200px;width:100%;object-fit:cover" />{{/event_image_id}}',
      },
      { token: "{{#event_image_id}} ... {{/event_image_id}}", description: "Show event image only when set" },
      { token: "{{event_image_id}}", description: "Event image id/url (prefer {{EVENT_IMAGE_URL}})" },
      { token: "{{event_image_url}}", description: "Event image URL alias" },
    ],
  },
  {
    title: "Facilities",
    items: [
      { token: "{{#facilities}} ... {{/facilities}}", description: "Hidden if no amenities" },
      { token: "{{facility_displaytext}}", description: "Amenity label" },
    ],
  },
  {
    title: "Photo gallery",
    items: [
      { token: "{{#locationimages}} ... {{/locationimages}}", description: "Hidden if no photos" },
      {
        token: "{{LOCATION_IMAGE_URL}}",
        description: "Full gallery image URL — prefer this",
        example:
          '{{#locationimages}}<img src="{{LOCATION_IMAGE_URL}}" alt="Gallery" style="max-height:220px;width:100%;object-fit:cover" />{{/locationimages}}',
      },
      {
        token: "{{location_image_id}}",
        description: "Gallery image id/url (legacy; prefer {{LOCATION_IMAGE_URL}})",
      },
    ],
  },
  {
    title: "Video gallery",
    items: [
      {
        token: "{{#locationvideos}} ... {{/locationvideos}}",
        description: "One video per location; hidden when no video URLs",
      },
      {
        token: "{{LOCATION_VIDEO_EMBED_URL}}",
        description: "Embed-safe YouTube, Vimeo, or hosted-video URL (iframe src only)",
        example:
          '{{#locationvideos}}<iframe src="{{LOCATION_VIDEO_EMBED_URL}}" title="Business video" loading="lazy" allowfullscreen></iframe>{{/locationvideos}}',
      },
      {
        token: "{{LOCATION_VIDEO_URL}}",
        description: "Original video URL for a normal link (not iframe src)",
      },
    ],
  },
  {
    title: "Customer reviews",
    items: [
      {
        token: "{{#reviews}} ... {{/reviews}}",
        description: "Shows when review data exists — for editable quotes use static Testimonials block",
      },
      { token: "{{rating_stars}}", description: "Star rating display" },
      { token: "{{comment}}", description: "Review text" },
    ],
  },
  {
    title: "Rooms (Hospitality)",
    items: [
      { token: "{{#hasrooms}} ... {{/hasrooms}}", description: "Wrap rooms section — hidden if no rooms" },
      { token: "{{#rooms}} ... {{/rooms}}", description: "One room card per iteration — never put section title inside loop" },
      { token: "{{room.id}}", description: "Room booking code / id" },
      { token: "{{room.room_number}}", description: "Room number" },
      { token: "{{room.room_name}}", description: "Room name field" },
      { token: "{{room.name}}", description: "Display name" },
      { token: "{{room.type}}", description: "Room type (double, suite, etc.)" },
      { token: "{{room.capacity}}", description: "Max guests" },
      { token: "{{room.price}}", description: "Price per night" },
      { token: "{{room.main_photo}}", description: "Room photo URL" },
      { token: "{{room.video_url}}", description: "Room video URL" },
      { token: "{{room.status}}", description: "Status code" },
      { token: "{{room.status_label}}", description: "Human-readable status" },
      { token: "{{#if_room_available}} ... {{/if_room_available}}", description: "Inside rooms loop — show Book when available" },
      { token: "{{#if_room_unavailable}} ... {{/if_room_unavailable}}", description: "Inside rooms loop — show status when not bookable" },
      { token: "{{ROOM_BOOK_URL}}", description: "Book this room (inside rooms loop)" },
    ],
  },
  {
    title: "Policies (Hospitality)",
    items: [
      { token: "{{hospitality.check_in_time}}", description: "Default check-in time" },
      { token: "{{hospitality.check_out_time}}", description: "Default check-out time" },
      { token: "{{hospitality.cancellation_policy}}", description: "Cancellation policy text" },
      { token: "{{hospitality.payment_policy}}", description: "Payment policy text" },
    ],
  },
  {
    title: "Packages (Hospitality)",
    items: [
      { token: "{{#haspackages}} ... {{/haspackages}}", description: "Wrap packages section — hidden if none" },
      { token: "{{#packages}} ... {{/packages}}", description: "One package card per iteration" },
      { token: "{{package.id}}", description: "Package id" },
      { token: "{{package.name}}", description: "Package name" },
      { token: "{{package.price}}", description: "Price label" },
      { token: "{{package.description}}", description: "Package description" },
      { token: "{{package.badge}}", description: "Badge label" },
      { token: "{{package.image_url}}", description: "Package image URL" },
      { token: "{{package.minimum_nights}}", description: "Minimum nights" },
      { token: "{{package.max_guests}}", description: "Max guests" },
      { token: "{{package.room_type}}", description: "Room type included" },
      { token: "{{package.includes}}", description: "Includes (joined text)" },
      { token: "{{PACKAGE_BOOK_URL}}", description: "Book this package" },
    ],
  },
  {
    title: "Food menu (Hospitality)",
    items: [
      { token: "{{#hasfoodmenu}} ... {{/hasfoodmenu}}", description: "Wrap food section — hidden if empty" },
      { token: "{{#food_menu}} ... {{/food_menu}}", description: "One menu item per iteration" },
      { token: "{{food.meal}}", description: "Meal type (breakfast, lunch, etc.)" },
      { token: "{{food.title}}", description: "Dish / menu title" },
      { token: "{{food.description}}", description: "Description" },
      { token: "{{food.cuisines}}", description: "Cuisines (comma-separated)" },
    ],
  },
  {
    title: "Nearby places (Hospitality)",
    items: [
      { token: "{{#hasnearby}} ... {{/hasnearby}}", description: "Wrap nearby section — hidden if empty" },
      { token: "{{#nearby_places}} ... {{/nearby_places}}", description: "One place card per iteration" },
      { token: "{{place.name}}", description: "Place name" },
      { token: "{{place.distance}}", description: "Distance from property" },
      { token: "{{place.travel_time}}", description: "Travel time" },
      { token: "{{place.icon}}", description: "Emoji or icon" },
      { token: "{{place.image_url}}", description: "Photo URL" },
      { token: "{{place.map_url}}", description: "Map / directions URL" },
    ],
  },
  {
    title: "Guest services (Hospitality)",
    items: [
      { token: "{{#hasguestservices}} ... {{/hasguestservices}}", description: "Wrap guest services — hidden if empty" },
      { token: "{{#guest_services}} ... {{/guest_services}}", description: "One guest service card per iteration" },
      { token: "{{guest.name}}", description: "Service name" },
      { token: "{{guest.price}}", description: "Price label" },
      { token: "{{guest.description}}", description: "Description" },
      { token: "{{guest.category}}", description: "Category" },
      { token: "{{guest.icon}}", description: "Icon / emoji" },
    ],
  },
  {
    title: "Contact form",
    items: [
      { token: 'class="az-form"', description: "Contact form — saves enquiries as leads" },
      { token: 'name="name" | email | phone | message"', description: "Required field names" },
    ],
  },
  {
    title: "Environment",
    items: [
      { token: "{{environment.baseurl}}", description: "API / files base URL" },
      { token: "data-appointza-book", description: "Add on Book / Register links (service appointments & events)" },
    ],
  },
];

export type TemplateBusinessContext = {
  organisationId: number;
  organisationName: string;
  organisationLogoId: number;
  locationId: number;
  locationName: string;
  userEmail?: string;
  /** Visual theme for the page (appended at the end of AI prompts). */
  theme?: string;
  /** Who the site is for — audience / business type (appended at the end of AI prompts). */
  siteFor?: string;
};

function businessDisplayName(ctx: TemplateBusinessContext): string {
  return ctx.organisationName?.trim() || "Your business";
}

export function buildVariablesReferenceText(): string {
  const lines: string[] = [
    "TEMPLATE VARIABLES REFERENCE",
    "============================",
    "",
    "Syntax: {{variable}} — replaced with live business data when the page is published.",
    "Loops: {{#block}} ... {{/block}} — repeat for each item; entire block hidden if list is empty.",
    "Conditionals: {{#block}} ... {{/block}} — show inner HTML only when that data exists.",
    "Use {{#hasrooms}}, {{#haspackages}}, {{#hasfoodmenu}}, {{#hasnearby}}, {{#hasguestservices}}, {{#hasevents}}, {{#hasservices}}, {{#hastimings}}, {{#hasfacilities}}, {{#haslocationimages}}, {{#haslocationvideos}}, {{#hasreviews}}, {{#haspolicies}} wrappers for optional sections.",
    "If a variable is empty, do not show that field or its parent section (no blank headings/cards).",
    "",
  ];

  for (const group of TEMPLATE_VARIABLE_GROUPS) {
    lines.push(group.title.toUpperCase());
    lines.push("-".repeat(group.title.length));
    for (const item of group.items) {
      lines.push(`  ${item.token}`);
      lines.push(`    ${item.description}`);
      if (item.example) lines.push(`    Example: ${item.example}`);
    }
    lines.push("");
  }

  return lines.join("\n").trim();
}

export function buildBusinessDataText(ctx: TemplateBusinessContext): string {
  const name = businessDisplayName(ctx);
  const orgId = ctx.organisationId > 0 ? ctx.organisationId : 0;
  const locId = ctx.locationId > 0 ? ctx.locationId : 0;
  const logoId = ctx.organisationLogoId > 0 ? ctx.organisationLogoId : 0;
  const bookPath =
    orgId > 0 && locId > 0
      ? buildBookAppointmentPath(orgId, locId)
      : "/book-appointment/{organisationId}/{locationId}";
  const serviceBookExample =
    orgId > 0 && locId > 0
      ? buildBookAppointmentPath(orgId, locId, 123)
      : "/book-appointment/{organisationId}/{locationId}?serviceId={serviceId}";
  const bookUrl =
    orgId > 0 && locId > 0
      ? `${getUiBaseUrl()}${bookPath}`
      : `${getUiBaseUrl()}/book-appointment/{organisationId}/{locationId}`;
  const roomBookExample =
    orgId > 0 && locId > 0
      ? `${getUiBaseUrl()}${buildRoomBookPath(orgId, locId, "room-201")}`
      : `${getUiBaseUrl()}/book?roomId=room-201&organisationId={organisationId}&locationId={locationId}`;
  const packageBookExample =
    orgId > 0 && locId > 0
      ? `${getUiBaseUrl()}/book?packageId=weekend-escape&organisationId=${orgId}&locationId=${locId}`
      : `${getUiBaseUrl()}/book?packageId={packageId}&organisationId={organisationId}&locationId={locationId}`;
  const apiBase = environment.baseurl || getApiBaseUrl();
  const logoUrl = logoId > 0 ? `${apiBase}/api/Files/Get?id=${logoId}` : "";

  return [
    "YOUR BUSINESS DATA",
    "==================",
    "",
    `Business name: ${name}`,
    ctx.locationName ? `Location: ${ctx.locationName}` : "",
    ctx.userEmail ? `Email: ${ctx.userEmail}` : "",
    orgId > 0 ? `Organisation ID: ${orgId}` : "",
    locId > 0 ? `Location ID: ${locId}` : "",
    logoId > 0
      ? `Logo file ID: ${logoId}`
      : "Logo: not uploaded — omit the entire {{#organizationlogo}} block",
    logoUrl ? `Logo image URL: ${logoUrl}` : "",
    `General booking page: ${bookUrl}`,
    `Per-service booking (example): ${getUiBaseUrl()}${serviceBookExample}`,
    `Room booking (example): ${roomBookExample}`,
    `Package booking (example): ${packageBookExample}`,
    `Image base URL: ${apiBase}`,
    "",
    "Hospitality: rooms, packages, food menu, nearby places, guest services, and policies are filled from Organization → Hospitality.",
    "Use {{ROOM_BOOK_URL}} and {{PACKAGE_BOOK_URL}} for stay bookings — not {{BOOKNOWURL}}.",
    "Inside a service loop use {{SERVICE_BOOK_URL}}, not {{BOOKNOWURL}}.",
    "",
    "Placeholders like {{organisationdetail.name}} are filled from this profile when the page goes live.",
    "If a section has no data (no events, no rooms, no gallery photos), hide that whole section with the matching {{#has*}} wrapper.",
  ]
    .filter(Boolean)
    .join("\n");
}

/** Appended at the end of HTML/Blocks AI prompts — theme + audience briefing. */
function buildAiPromptBriefingTail(ctx: TemplateBusinessContext): string {
  const name = ctx.organisationName?.trim() || "Your business";
  const location = ctx.locationName?.trim() || "";
  const theme =
    ctx.theme?.trim() ||
    "[WRITE THEME HERE — e.g. warm spa, modern clinic, luxury resort, bold gym]";
  const siteFor =
    ctx.siteFor?.trim() ||
    "[WRITE WHO THIS SITE IS FOR — e.g. women booking salon appointments, families booking resort stays, athletes booking coaching]";

  return [
    "",
    "## Design briefing (fill this in last — required)",
    "",
    "Read everything above first (variables, rules, booking links).",
    "Then design the page using ONLY this briefing:",
    "",
    `Business name: ${name}`,
    ...(location ? [`Location: ${location}`] : []),
    `Theme / visual style: ${theme}`,
    `Who this site is for: ${siteFor}`,
    "",
    "Instructions for the theme & audience:",
    "- Match colors, typography, imagery mood, and section tone to the Theme.",
    "- Write headlines, CTAs, and section copy for the people in “Who this site is for”.",
    "- Prefer live appointza data sections that fit this audience (services/events vs rooms/packages).",
    "- Keep the required section order: Hero → About → Services/Rooms → Events → Packages → Guest Services → Food Menu → Facilities → Business Hours → Policies → Nearby Places → Gallery → Videos → Reviews → Contact → Map/Location → Footer.",
    "- Do not invent fake business data; keep all Appointza variables exactly as listed above.",
    "- Make the first viewport feel like this brand for this audience — not a generic template.",
    "- If a variable or list is empty at runtime, that field/section must not appear (use {{#…}} wrappers — never leave blank headings or empty cards).",
    "- Include scroll motion (parallax, reveal-on-scroll, sticky/pin where it fits the theme) — see Motion rules above.",
  ].join("\n");
}

export function buildAiTemplatePrompt(ctx: TemplateBusinessContext): string {
  const orgId = ctx.organisationId > 0 ? ctx.organisationId : 0;
  const locId = ctx.locationId > 0 ? ctx.locationId : 0;
  const roomBookHint =
    orgId > 0 && locId > 0
      ? `${getUiBaseUrl()}${buildRoomBookPath(orgId, locId, "room-201")}`
      : "/book?roomId=room-201&organisationId={organisationId}&locationId={locationId}";

  return [
    "# Appointza Master Prompt",
    "",
    "## OUTPUT",
    "",
    "Return one complete HTML document with embedded CSS only.",
    "",
    "## IMPORTANT",
    "",
    "- Preserve ALL Appointza variables exactly as listed below.",
    "- Never invent or rename variables.",
    "- Never hardcode booking URLs, room IDs, or package IDs.",
    "- Do not use dead tokens: organisationdetail.organisationgstnumber, organizationemail.",
    "- Use organisationdetail.gstnumber and organisationemail.",
    "- Improve only the UI.",
    "- Return HTML only without Markdown or explanations.",
    "",
    "## Empty data — hide empty sections (MANDATORY)",
    "",
    "If a variable or list is empty at runtime, that content MUST NOT appear. Never show empty headings, blank paragraphs, empty cards, or sections with no items.",
    "",
    "Rules:",
    "- Wrap every optional SECTION (heading + content) in the matching list/has wrapper so the whole section disappears when data is missing.",
    "- Wrap every optional FIELD (tagline, notes, GST, email, address line 2, country, maps link, images, end date, etc.) in its {{#…}} conditional.",
    "- Do NOT output a section shell like `<section><h2>Events</h2>…</section>` outside `{{#hasevents}}` — put the entire section inside the wrapper.",
    "- Same for: `{{#hasrooms}}`, `{{#haspackages}}`, `{{#hasfoodmenu}}`, `{{#hasnearby}}`, `{{#hasguestservices}}`, `{{#hasevents}}`, `{{#hasservices}}`, `{{#hastimings}}`, `{{#hasfacilities}}`, `{{#haslocationimages}}`, `{{#haslocationvideos}}`, `{{#hasreviews}}`, `{{#haspolicies}}`, `{{#orgnaisatinservice}}`, `{{#OrganisationServiceTiming}}`, `{{#facilities}}`, `{{#locationimages}}`, `{{#locationvideos}}`, `{{#reviews}}`, `{{#organizationlogo}}`, `{{#gstnumber}}`, `{{#googlemaps}}`, `{{#coordinates}}`, `{{#addressline2}}`, `{{#country}}`, `{{#service_image_id}}`, `{{#event_image_id}}`, `{{#to_date}}`, `{{#organisationtagline}}`, `{{#organisationnotes}}`, `{{#organisationemail}}`.",
    "- Policies: wrap with {{#haspolicies}}; never leave blank policy paragraphs.",
    "- About/hero copy: wrap tagline/notes with {{#organisationtagline}} / {{#organisationnotes}} — never leave empty `<p>` tags.",
    "- Never invent placeholder text to “fill” missing live data.",
    "",
    "## Motion & scroll experience (REQUIRED for HTML)",
    "",
    "Build a scroll-led page (Apple-style polish). Use vanilla CSS + a small inline `<script>` only — no external animation libraries.",
    "Include several of these patterns (at least 4), tuned to the theme:",
    "",
    "1. **Scroll-driven animations** — progress tied to scroll (CSS `animation-timeline: scroll()` / `view()` where supported, with JS fallback using scroll position).",
    "2. **Parallax scrolling** — hero/background image or layers move slower/faster than foreground content (`transform: translateY` from scroll).",
    "3. **Scroll-triggered animations** — elements fade/slide/scale in when they enter the viewport (IntersectionObserver; class like `.is-inview`).",
    "4. **Sticky + scroll animation** — a sticky panel stays fixed while sibling content or captions change as the user scrolls through a tall track.",
    "5. **Image sequence / frame animation (optional highlight)** — one showcase section swaps images (or background-position frames) based on scroll progress through that section (use gallery `{{#locationimages}}` URLs when available; never invent image URLs).",
    "6. **Smooth reveal / fade transitions** — text and cards fade, slide, or scale into view with staggered delays.",
    "7. **Pinning / sticky sections** — pin a section (`position: sticky`) while the next beat of animation plays, then release.",
    "",
    "Motion rules:",
    "- Prefer `transform` and `opacity` (GPU-friendly); avoid layout thrash.",
    "- Respect `prefers-reduced-motion: reduce` — disable or simplify motion.",
    "- Keep Book / Register CTAs always readable; never hide booking links behind unfinished animations.",
    "- Do not break Mustache tokens inside JS strings incorrectly — keep `{{variables}}` in HTML attributes/content as usual.",
    "- Motion must enhance the brand; do not add noisy endless loops unrelated to scroll.",
    "",
    "## Business type",
    "",
    "- **Service businesses** (salon, clinic, gym): Services, Hours, Events, Gallery, {{BOOKNOWURL}} / {{SERVICE_BOOK_URL}}.",
    "- **Hospitality / stay** (hotel, resort, homestay): Rooms, Packages, Policies, Food menu, Nearby places, Guest services.",
    "- Wrap optional sections with {{#hasrooms}}, {{#haspackages}}, {{#hasfoodmenu}}, {{#hasnearby}}, {{#hasguestservices}}, {{#hasevents}}.",
    "- Use {{ROOM_BOOK_URL}} and {{PACKAGE_BOOK_URL}} for stay bookings — never {{BOOKNOWURL}} on room/package buttons.",
    "- Inside {{#orgnaisatinservice}} use {{SERVICE_BOOK_URL}} for the Book button — not {{BOOKNOWURL}}.",
    "",
    "## Required section order (top → bottom)",
    "",
    "Build the page in this exact order. Skip (omit entirely) a section when its data wrapper would be empty; do not reorder and do not leave empty placeholders.",
    "",
    "1. Hero",
    "2. About",
    "3. Services / Rooms (services for service businesses; rooms for hospitality)",
    "4. Events",
    "5. Packages (hospitality)",
    "6. Guest Services (hospitality)",
    "7. Food Menu (hospitality)",
    "8. Facilities",
    "9. Business Hours",
    "10. Policies (hospitality)",
    "11. Nearby Places (hospitality)",
    "12. Gallery",
    "13. Videos",
    "14. Reviews",
    "15. Contact",
    "16. Map / Location",
    "17. Footer",
    "",
    "## Variables",
    "",
    "### Organisation",
    "",
    "{{organisationdetail.id}}",
    "{{organisationdetail.name}}",
    "{{organisationdetail.tagline}}",
    "{{organisationdetail.notes}}",
    "{{organisation.notes}}",
    "{{OrganisationNotes}}",
    "{{organisationdetail.organisationlogo}}",
    "{{ORGANISATION_LOGO_URL}}",
    "{{organisationdetail.gstnumber}}",
    "{{organisationemail}}",
    "{{currentyear}}",
    "{{#organizationlogo}}{{/organizationlogo}}",
    "{{#gstnumber}}{{/gstnumber}}",
    "{{#organisationtagline}}{{/organisationtagline}}",
    "{{#organisationnotes}}{{/organisationnotes}}",
    "{{#organisationemail}}{{/organisationemail}}",
    "",
    "### Location",
    "",
    "{{locationdetail.id}}",
    "{{locationdetail.name}}",
    "{{locationdetail.addressline1}}",
    "{{locationdetail.addressline2}}",
    "{{locationdetail.city}}",
    "{{locationdetail.state}}",
    "{{locationdetail.country}}",
    "{{locationdetail.pincode}}",
    "{{locationdetail.latitude}}",
    "{{locationdetail.longitude}}",
    "{{locationdetail.googlelocation}}",
    "{{locationdetail.mobile}}",
    "{{#googlemaps}}{{/googlemaps}}",
    "{{#coordinates}}{{/coordinates}}",
    "{{#country}}{{/country}}",
    "{{#addressline2}}{{/addressline2}}",
    "",
    "### Booking URLs",
    "",
    "{{BOOKNOWURL}} — general service appointment booking",
    "{{SERVICE_BOOK_URL}} — per-service booking (inside {{#orgnaisatinservice}} only)",
    "{{EVENTBOOKURL}} — event registration (inside {{#events}})",
    "{{ROOM_BOOK_URL}} — book a specific room (inside {{#rooms}} only)",
    "{{PACKAGE_BOOK_URL}} — book a stay package (inside {{#packages}} only)",
    "",
    "Resolved room URL shape (do not hardcode):",
    roomBookHint,
    "",
    "### Services",
    "",
    "{{#hasservices}}",
    "{{#orgnaisatinservice}}",
    "{{Servicename}}",
    "{{prize}}",
    "{{timetaken}}",
    "{{notes}}",
    "{{service_id}}",
    "{{SERVICE_BOOK_URL}}",
    "{{SERVICE_IMAGE_URL}}",
    "{{#service_image_id}}{{/service_image_id}}",
    "{{service_image_id}}",
    "{{/orgnaisatinservice}}",
    "{{/hasservices}}",
    "",
    "### Business Hours",
    "",
    "{{#hastimings}}",
    "{{#OrganisationServiceTiming}}",
    "{{day_name}}",
    "{{day_of_week}}",
    "{{start_time}}",
    "{{end_time}}",
    "{{/OrganisationServiceTiming}}",
    "{{/hastimings}}",
    "",
    "### Events",
    "",
    "{{#hasevents}}",
    "{{#events}}",
    "{{event_name}}",
    "{{event_date}}",
    "{{from_date}}",
    "{{to_date}}",
    "{{#to_date}}{{/to_date}}",
    "{{entry_amount}}",
    "{{remainingslot}}",
    "{{description}}",
    "{{status}}",
    "{{EVENTBOOKURL}}",
    "{{EVENT_IMAGE_URL}}",
    "{{#event_image_id}}{{/event_image_id}}",
    "{{event_image_id}}",
    "{{event_image_url}}",
    "{{/events}}",
    "{{/hasevents}}",
    "",
    "### Facilities",
    "",
    "{{#hasfacilities}}",
    "{{#facilities}}",
    "{{facility_displaytext}}",
    "{{/facilities}}",
    "{{/hasfacilities}}",
    "",
    "### Gallery",
    "",
    "{{#haslocationimages}}",
    "{{#locationimages}}",
    "{{LOCATION_IMAGE_URL}}",
    "{{location_image_id}}",
    "{{/locationimages}}",
    "{{/haslocationimages}}",
    "",
    "### Videos",
    "",
    "{{#haslocationvideos}}",
    "{{#locationvideos}}",
    "{{LOCATION_VIDEO_EMBED_URL}}",
    "{{LOCATION_VIDEO_URL}}",
    "{{/locationvideos}}",
    "{{/haslocationvideos}}",
    "",
    "### Reviews (only when review data exists)",
    "",
    "{{#hasreviews}}",
    "{{#reviews}}",
    "{{rating_stars}}",
    "{{comment}}",
    "{{/reviews}}",
    "{{/hasreviews}}",
    "",
    "### Rooms (Hospitality)",
    "",
    "{{#hasrooms}}",
    "{{#rooms}}",
    "{{room.id}}",
    "{{room.room_number}}",
    "{{room.room_name}}",
    "{{room.name}}",
    "{{room.type}}",
    "{{room.capacity}}",
    "{{room.price}}",
    "{{room.main_photo}}",
    "{{room.video_url}}",
    "{{room.status}}",
    "{{room.status_label}}",
    "{{#if_room_available}}",
    "{{ROOM_BOOK_URL}}",
    "{{/if_room_available}}",
    "{{#if_room_unavailable}}",
    "{{/if_room_unavailable}}",
    "{{/rooms}}",
    "{{/hasrooms}}",
    "",
    "### Policies (Hospitality)",
    "",
    "{{#haspolicies}}",
    "{{hospitality.check_in_time}}",
    "{{hospitality.check_out_time}}",
    "{{hospitality.cancellation_policy}}",
    "{{hospitality.payment_policy}}",
    "{{/haspolicies}}",
    "",
    "### Packages (Hospitality)",
    "",
    "{{#haspackages}}",
    "{{#packages}}",
    "{{package.id}}",
    "{{package.name}}",
    "{{package.price}}",
    "{{package.description}}",
    "{{package.badge}}",
    "{{package.image_url}}",
    "{{package.minimum_nights}}",
    "{{package.max_guests}}",
    "{{package.room_type}}",
    "{{package.includes}}",
    "{{PACKAGE_BOOK_URL}}",
    "{{/packages}}",
    "{{/haspackages}}",
    "",
    "### Food menu (Hospitality)",
    "",
    "{{#hasfoodmenu}}",
    "{{#food_menu}}",
    "{{food.meal}}",
    "{{food.title}}",
    "{{food.description}}",
    "{{food.cuisines}}",
    "{{/food_menu}}",
    "{{/hasfoodmenu}}",
    "",
    "### Nearby places (Hospitality)",
    "",
    "{{#hasnearby}}",
    "{{#nearby_places}}",
    "{{place.name}}",
    "{{place.distance}}",
    "{{place.travel_time}}",
    "{{place.icon}}",
    "{{place.image_url}}",
    "{{place.map_url}}",
    "{{/nearby_places}}",
    "{{/hasnearby}}",
    "",
    "### Guest services (Hospitality)",
    "",
    "{{#hasguestservices}}",
    "{{#guest_services}}",
    "{{guest.name}}",
    "{{guest.price}}",
    "{{guest.description}}",
    "{{guest.category}}",
    "{{guest.icon}}",
    "{{/guest_services}}",
    "{{/hasguestservices}}",
    "",
    "### Environment",
    "",
    "{{environment.baseurl}}",
    "data-appointza-book",
    "",
    "## Rules",
    "",
    "- Only cards or media items repeat inside loops.",
    "- Never put sections, headings, grids, or outer containers inside loops.",
    "- Use CSS Grid and Flexbox.",
    "- Use a mobile-first responsive design.",
    "- Keep sections in this order: Hero → About → Services/Rooms → Events → Packages → Guest Services → Food Menu → Facilities → Business Hours → Policies → Nearby Places → Gallery → Videos → Reviews → Contact → Map/Location → Footer.",
    "- Skip (omit) a section entirely when its list/has wrapper has no items or its fields would all be empty — never show blank headings or empty cards.",
    "- Never create fake services, rooms, packages, events, images, videos, reviews, or addresses.",
    "- Hide optional sections when their {{#has*}} / list wrapper has no items.",
    "- Include scroll motion (parallax, reveal-on-scroll, sticky/pin, optional frame sequence) with reduced-motion support.",
    "",
    "### Booking links",
    "",
    "General service appointment:",
    "",
    '<a href="{{BOOKNOWURL}}" data-appointza-book>Book now</a>',
    "",
    "Per-service (inside {{#orgnaisatinservice}}):",
    "",
    '<a href="{{SERVICE_BOOK_URL}}" data-appointza-book>Book</a>',
    "",
    "Event registration:",
    "",
    '<a href="{{EVENTBOOKURL}}" data-appointza-book>Register</a>',
    "",
    "Room (always show Book — availability is checked on /book by dates, never show Occupied on the public page):",
    "",
    '<a href="{{ROOM_BOOK_URL}}">Book now</a>',
    "",
    "Do not show {{room.status_label}} or Occupied/Reserved badges on the public template. Prefer a plain Book now link (you may still wrap with {{#if_room_available}} which is always true for bookable rooms).",
    "",
    "Package (inside {{#packages}} loop):",
    "",
    '<a href="{{PACKAGE_BOOK_URL}}">Book package</a>',
    "",
    "Never link booking buttons to `/explore`, `#services`, or invented URLs.",
    "",
    "### Logo",
    "",
    "Prefer ORGANISATION_LOGO_URL inside the logo conditional:",
    "",
    "{{#organizationlogo}}",
    '<img src="{{ORGANISATION_LOGO_URL}}" alt="{{organisationdetail.name}}">',
    "{{/organizationlogo}}",
    "",
    "### Service image",
    "",
    "Prefer SERVICE_IMAGE_URL:",
    "",
    "{{#service_image_id}}",
    '<img src="{{SERVICE_IMAGE_URL}}" alt="{{Servicename}}">',
    "{{/service_image_id}}",
    "",
    "### Gallery",
    "",
    "Wrap the ENTIRE Gallery section so it disappears when there are no photos:",
    "",
    "{{#haslocationimages}}",
    '<section id="gallery" class="az-reveal">',
    "  <h2>Gallery</h2>",
    '  <div class="gallery-grid">',
    "    {{#locationimages}}",
    '    <img src="{{LOCATION_IMAGE_URL}}" alt="{{organisationdetail.name}} gallery" loading="lazy">',
    "    {{/locationimages}}",
    "  </div>",
    "</section>",
    "{{/haslocationimages}}",
    "",
    "### Videos",
    "",
    "Wrap the ENTIRE Videos section. Use `{{LOCATION_VIDEO_EMBED_URL}}` only as the iframe source.",
    "Make video iframes responsive with aspect-ratio 16/9 and width 100%.",
    "",
    "{{#haslocationvideos}}",
    '<section id="videos" class="az-reveal">',
    "  <h2>Videos</h2>",
    '  <div class="videos-grid">',
    "    {{#locationvideos}}",
    '    <div class="video-card">',
    "      <iframe",
    '        src="{{LOCATION_VIDEO_EMBED_URL}}"',
    '        title="{{organisationdetail.name}} video"',
    '        loading="lazy"',
    '        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"',
    "        allowfullscreen>",
    "      </iframe>",
    '      <a href="{{LOCATION_VIDEO_URL}}" target="_blank" rel="noopener noreferrer">Watch video</a>',
    "    </div>",
    "    {{/locationvideos}}",
    "  </div>",
    "</section>",
    "{{/haslocationvideos}}",
    "",
    "### Rooms (Hospitality)",
    "",
    "Section and grid OUTSIDE the loop. One room card inside {{#rooms}}:",
    "",
    "{{#hasrooms}}",
    '<section id="rooms" class="az-reveal">',
    "  <h2>Our rooms</h2>",
    '  <div class="rooms-grid">',
    "    {{#rooms}}",
    '    <article class="room-card">',
    '      <img src="{{room.main_photo}}" alt="{{room.name}}" loading="lazy">',
    "      <h3>{{room.name}}</h3>",
    "      <p>{{room.type}} · {{room.capacity}} guests</p>",
    "      <p>From ₹{{room.price}} / night</p>",
    '      <a href="{{ROOM_BOOK_URL}}">Book now</a>',
    "    </article>",
    "    {{/rooms}}",
    "  </div>",
    "</section>",
    "{{/hasrooms}}",
    "",
    "Never show Occupied / Reserved / status badges on the public rooms section — guests pick dates on the booking page.",
    "",
    "### Packages (Hospitality)",
    "",
    "{{#haspackages}}",
    '<section id="packages" class="az-reveal">',
    "  <h2>Packages</h2>",
    '  <div class="packages-grid">',
    "    {{#packages}}",
    '    <article class="package-card">',
    '      <img src="{{package.image_url}}" alt="{{package.name}}" loading="lazy">',
    "      <h3>{{package.name}}</h3>",
    "      <p>{{package.price}}</p>",
    "      <p>{{package.description}}</p>",
    '      <a href="{{PACKAGE_BOOK_URL}}">Book package</a>',
    "    </article>",
    "    {{/packages}}",
    "  </div>",
    "</section>",
    "{{/haspackages}}",
    "",
    "### Guest services (Hospitality)",
    "",
    "{{#hasguestservices}}",
    '<section id="guest-services" class="az-reveal">',
    "  <h2>Guest services</h2>",
    '  <div class="guest-services-grid">',
    "    {{#guest_services}}",
    '    <article class="guest-service-card">',
    "      <span>{{guest.icon}}</span>",
    "      <h3>{{guest.name}}</h3>",
    "      <p>{{guest.price}}</p>",
    "      <p>{{guest.category}}</p>",
    "      <p>{{guest.description}}</p>",
    "    </article>",
    "    {{/guest_services}}",
    "  </div>",
    "</section>",
    "{{/hasguestservices}}",
    "",
    "### Policies (Hospitality)",
    "",
    "Omit Policies when empty — wrap the entire section:",
    "",
    "{{#haspolicies}}",
    '<section id="policies" class="az-reveal">',
    "  <h2>Policies</h2>",
    "  <p>Check-in {{hospitality.check_in_time}} · Check-out {{hospitality.check_out_time}}</p>",
    "  <p>{{hospitality.cancellation_policy}}</p>",
    "  <p>{{hospitality.payment_policy}}</p>",
    "</section>",
    "{{/haspolicies}}",
    "",
    "### Services section",
    "",
    "{{#hasservices}}",
    '<section id="services" class="az-reveal">',
    "  <h2>Our services</h2>",
    '  <div class="services-grid">',
    "    {{#orgnaisatinservice}}",
    '    <article class="service-card">…</article>',
    "    {{/orgnaisatinservice}}",
    "  </div>",
    "</section>",
    "{{/hasservices}}",
    "",
    "### Hours / Events / Facilities / Reviews",
    "",
    "Same pattern — wrap entire sections with {{#hastimings}}, {{#hasevents}}, {{#hasfacilities}}, {{#hasreviews}}.",
    "Optional fields: {{#organisationtagline}}…{{/organisationtagline}}, {{#organisationnotes}}…{{/organisationnotes}}.",
    "",
    "### Map",
    "",
    "Build the map embed from coordinates using `output=embed`. Never use a `/maps/embed?pb=` URL.",
    "Never put `{{locationdetail.googlelocation}}` in an iframe source; it is a link only.",
    "",
    "Map iframe (only inside {{#coordinates}}):",
    "",
    "{{#coordinates}}",
    '<div class="map-wrap">',
    "  <iframe",
    '    title="{{locationdetail.name}} map"',
    '    loading="lazy"',
    '    referrerpolicy="no-referrer-when-downgrade"',
    "    allowfullscreen",
    '    src="https://www.google.com/maps?q={{locationdetail.latitude}},{{locationdetail.longitude}}&output=embed">',
    "  </iframe>",
    "</div>",
    "{{/coordinates}}",
    "",
    "Directions link (only inside {{#googlemaps}}):",
    "",
    "{{#googlemaps}}",
    '<a href="{{locationdetail.googlelocation}}" target="_blank" rel="noopener">View on Google Maps</a>',
    "{{/googlemaps}}",
    "",
    "### Contact form",
    "",
    "The contact form must use:",
    "",
    '<form class="az-form">',
    '  <input name="name" type="text" required>',
    '  <input name="email" type="email" required>',
    '  <input name="phone" type="tel">',
    '  <textarea name="message" required></textarea>',
    '  <button type="submit">Send message</button>',
    "</form>",
    "",
    "## Validation",
    "",
    "- Exactly one Hero.",
    "- Sections appear in the required order listed above (omit empty-data sections; never reorder).",
    "- Exactly one Services section (for service businesses) OR Rooms section (for hospitality).",
    "- Only service cards repeat inside the service loop.",
    "- Only gallery images repeat inside the gallery loop (use LOCATION_IMAGE_URL).",
    "- Only video cards repeat inside the video loop.",
    "- Only room cards repeat inside {{#rooms}}; only package cards inside {{#packages}}.",
    "- Only guest service cards repeat inside {{#guest_services}}.",
    "- Every optional section/field uses a {{#…}} wrapper so empty data shows nothing.",
    "- No empty headings, empty cards, or blank policy/about paragraphs.",
    "- Scroll motion present (parallax and/or sticky/pin and reveal-on-scroll); respects prefers-reduced-motion.",
    "- Map iframe uses output=embed, never pb.",
    "- {{locationdetail.googlelocation}} is used only in an <a href>.",
    "- Logo uses ORGANISATION_LOGO_URL inside {{#organizationlogo}}.",
    "- Per-service Book uses SERVICE_BOOK_URL.",
    "- No nested sections.",
    "- No repeated headings.",
    "- No invented or altered variables.",
    "- No hardcoded booking URLs.",
    "- Return HTML only.",
    buildAiPromptBriefingTail(ctx),
  ].join("\n");
}

/** AI prompt that returns TemplateBuilderProject JSON (blocks mode). */
export function buildAiBlockTemplatePrompt(ctx: TemplateBusinessContext): string {
  const name = ctx.organisationName?.trim() || "your business";
  const liveBlocks = [
    "appointza-organization — Business home / name, logo, about, Book (variant 1–4, showLogo, showGst) — can act as Hero",
    "appointza-services — Services catalog (variant 1–4)",
    "appointza-rooms — Rooms for this location (variant 1–4)",
    "appointza-events — Events & workshops (variant 1–4)",
    "appointza-hospitality-packages — Stay packages (variant 1–4)",
    "appointza-guest-services — Guest services & add-ons (variant 1–4)",
    "appointza-food-menu — Food & dining menu (variant 1–4)",
    "appointza-facilities — Amenities / facilities (variant 1–4)",
    "appointza-timings — Working hours / Business Hours (variant 1–4)",
    "appointza-hospitality-policies — Cancellation, payment, check-in/out (variant 1–4)",
    "appointza-nearby-places — Nearby attractions (variant 1–4)",
    "appointza-location-images — Photo gallery (variant 1–4)",
    "appointza-location-videos — Video gallery (variant 1–4)",
    "appointza-reviews — Customer reviews when review data exists (variant 1–4); prefer testimonials for editable quotes",
    "appointza-location — Address, phone, map (variant 1–4)",
  ];
  const staticBlocks = [
    "header, section, footer",
    "hero, hero-2, hero-3, hero-4, hero-5, hero-6",
    "about, features, stats, logos, timeline",
    "pricing, membership, media, gallery, testimonials",
    "cta-booking, time-slots, live-status",
    "form, map, social, faq, team, offers",
    "blog, announcements, search, filters, support",
    "privacy, terms, policy, careers, auth, dashboard",
    "loyalty, download-app, newsletter, payment-info",
    "float-whatsapp, float-call",
  ];

  return [
    "# Appointza Blocks Master Prompt",
    "",
    `Design a booking page for "${name}" as a block project JSON (not free-form HTML).`,
    "",
    "## OUTPUT",
    "",
    "Return ONLY valid JSON matching this shape (no Markdown fences, no commentary):",
    "",
    "{",
    '  "builderVersion": 2,',
    '  "pages": {',
    '    "home": {',
    '      "id": "home",',
    '      "name": "Home",',
    '      "blocks": [',
    "        {",
    '          "id": "unique-string",',
    '          "type": "block-type",',
    '          "visible": true,',
    '          "data": {}',
    "        }",
    "      ]",
    "    }",
    "  }",
    "}",
    "",
    "## IMPORTANT",
    "",
    "- Prefer live `appointza-*` blocks for real business data.",
    "- Do not invent services, rooms, packages, prices, photos, reviews, or addresses inside block data.",
    "- For live blocks, `data` may only include layout flags (e.g. variant, showLogo, showGst).",
    "- For static blocks, you may edit marketing copy in `data`, and may use {{variables}} in text fields.",
    "- When using variables in static text, prefer working tokens: organisationdetail.gstnumber, organisationemail, ORGANISATION_LOGO_URL, LOCATION_IMAGE_URL, SERVICE_BOOK_URL, SERVICE_IMAGE_URL.",
    "- Never use organisationdetail.organisationgstnumber or organizationemail.",
    "- Every block needs a unique `id`, a known `type`, `visible: true`, and a `data` object.",
    "- Order blocks top-to-bottom for a complete page.",
    "- Return JSON only.",
    "",
    "## Empty data — hide empty sections (MANDATORY)",
    "",
    "Live `appointza-*` blocks already hide empty lists via Mustache wrappers. Still:",
    "- Prefer the live block for that data type instead of inventing static fake lists.",
    "- Do NOT add a live block for content the business type does not use (e.g. skip rooms/packages for a pure salon).",
    "- Skip optional live blocks that would render empty shells for this business type.",
    "- In static block text fields, wrap optional variables with {{#…}}{{/…}} so empty values do not leave blank lines (tagline, notes, GST, email, address line 2, etc.).",
    "- Set `showLogo: false` when no logo should show; set `showGst: true` only when GST should appear inside {{#gstnumber}}.",
    "- Never invent placeholder copy to fill missing live data.",
    "",
    "## Motion & scroll experience (Blocks)",
    "",
    "Blocks render as sections; design for a scroll-led page:",
    "- Start with a full-viewport hero (`hero` / `hero-2`… or `appointza-organization`) as the first composition.",
    "- Prefer variants and block order that create clear scroll rhythm (hero → about → catalog → proof → contact).",
    "- Use sticky-friendly structure: hero full-bleed, then content sections that reveal as the user scrolls.",
    "- For static heroes/CTAs, write concise copy that works with fade/slide reveals once converted to HTML.",
    "- Mention in block `data` titles/subtitles only; do not invent fake image URLs for parallax/frame sequences.",
    "- If you add a static `gallery` or `media` block, keep image fields empty unless using live `appointza-location-images` — gallery motion uses live photos.",
    "- Floating widgets (`float-whatsapp`, `float-call`) stay fixed; they are not part of scroll pinning.",
    "",
    "## Business type",
    "",
    "- **Service business** (salon, clinic, gym): appointza-services, appointza-timings, appointza-events, appointza-location-images, appointza-location-videos.",
    "- **Hospitality / stay** (hotel, resort, homestay): appointza-rooms, appointza-hospitality-packages, appointza-hospitality-policies, appointza-food-menu, appointza-nearby-places, appointza-guest-services. Skip appointza-services unless the org also sells services.",
    "",
    "## Required page order (top → bottom)",
    "",
    "Order blocks exactly like this. Skip a block entirely when that data does not apply (so empty sections never appear); do not reorder.",
    "",
    "1. Hero — `hero` / `hero-2`… or `appointza-organization`",
    "2. About — `about` or `section`",
    "3. Services / Rooms — `appointza-services` OR `appointza-rooms`",
    "4. Events — `appointza-events`",
    "5. Packages — `appointza-hospitality-packages` (hospitality)",
    "6. Guest Services — `appointza-guest-services` (hospitality)",
    "7. Food Menu — `appointza-food-menu` (hospitality)",
    "8. Facilities — `appointza-facilities`",
    "9. Business Hours — `appointza-timings`",
    "10. Policies — `appointza-hospitality-policies` (hospitality)",
    "11. Nearby Places — `appointza-nearby-places` (hospitality)",
    "12. Gallery — `appointza-location-images`",
    "13. Videos — `appointza-location-videos`",
    "14. Reviews — `testimonials` (preferred) or `appointza-reviews`",
    "15. Contact — `form` (and/or `cta-booking`)",
    "16. Map / Location — `appointza-location` (and/or `map`)",
    "17. Footer — `footer`",
    "",
    "Optional `header` may appear before Hero. Floating widgets (`float-whatsapp`, `float-call`) may appear after Footer.",
    "",
    "## Recommended page order — service business",
    "",
    "1. hero (or appointza-organization)",
    "2. about",
    "3. appointza-services",
    "4. appointza-events",
    "5. appointza-facilities",
    "6. appointza-timings",
    "7. appointza-location-images",
    "8. appointza-location-videos",
    "9. testimonials (or appointza-reviews)",
    "10. form",
    "11. appointza-location",
    "12. footer",
    "",
    "## Recommended page order — hospitality / stay",
    "",
    "1. hero (or appointza-organization)",
    "2. about",
    "3. appointza-rooms",
    "4. appointza-events",
    "5. appointza-hospitality-packages",
    "6. appointza-guest-services",
    "7. appointza-food-menu",
    "8. appointza-facilities",
    "9. appointza-timings",
    "10. appointza-hospitality-policies",
    "11. appointza-nearby-places",
    "12. appointza-location-images",
    "13. appointza-location-videos",
    "14. testimonials (or appointza-reviews)",
    "15. form",
    "16. appointza-location",
    "17. footer",
    "",
    "## Allowed live block types",
    "",
    ...liveBlocks.map((line) => `- ${line}`),
    "",
    "## Allowed static block types",
    "",
    ...staticBlocks.map((line) => `- ${line}`),
    "",
    "## Example live block",
    "",
    "{",
    '  "id": "appointza-services-1",',
    '  "type": "appointza-services",',
    '  "visible": true,',
    '  "data": { "variant": 2 }',
    "}",
    "",
    "## Example hospitality live blocks",
    "",
    "{",
    '  "id": "appointza-rooms-1",',
    '  "type": "appointza-rooms",',
    '  "visible": true,',
    '  "data": { "variant": 1 }',
    "}",
    "",
    "{",
    '  "id": "appointza-guest-services-1",',
    '  "type": "appointza-guest-services",',
    '  "visible": true,',
    '  "data": { "variant": 1 }',
    "}",
    "",
    "{",
    '  "id": "appointza-location-videos-1",',
    '  "type": "appointza-location-videos",',
    '  "visible": true,',
    '  "data": { "variant": 1 }',
    "}",
    "",
    "## Example static hero",
    "",
    "{",
    '  "id": "hero-1",',
    '  "type": "hero",',
    '  "visible": true,',
    '  "data": {',
    '    "title": "{{organisationdetail.name}}",',
    '    "subtitle": "{{organisationdetail.tagline}}",',
    '    "buttonText": "Book appointment",',
    '    "useLiveBookUrl": true',
    "  }",
    "}",
    "",
    "## Validation",
    "",
    "- builderVersion must be 2",
    "- pages.home.blocks must be a non-empty array",
    "- Blocks must follow the required page order (omit empty/non-applicable sections; never reorder)",
    "- No live blocks that would leave empty section shells for this business type",
    "- Optional static text uses {{#…}} wrappers so empty variables show nothing",
    "- Scroll-friendly page rhythm (full-viewport hero + clear section beats)",
    "- Use only allowed block types",
    "- No invented variables or hardcoded booking URLs",
    "- Return JSON only",
    buildAiPromptBriefingTail(ctx),
  ].join("\n");
}
